version: '3.8'
services:
  postgres:
    container_name: cipher-link
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data:
