import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/layout/header";
import { ThemeProvider } from "next-themes";
import { Providers } from "@/components/ui/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col`}
      >
        <Providers>
          <Header />
          <main className="mx-auto max-w-5xl flex-1 px-4">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
